// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: github.com/shashank-razor/DownloadManager/rpc/downloadManager/service.proto

package downloadManager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Urls []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DownloadRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto protoreflect.FileDescriptor

var file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDesc = []byte{
	0x0a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x61,
	0x73, 0x68, 0x61, 0x6e, 0x6b, 0x2d, 0x72, 0x61, 0x7a, 0x6f, 0x72, 0x2f, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x22, 0x39,
	0x0a, 0x0f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x5e, 0x0a,
	0x0a, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x09, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a,
	0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x73,
	0x68, 0x61, 0x6e, 0x6b, 0x2d, 0x72, 0x61, 0x7a, 0x6f, 0x72, 0x2f, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescOnce sync.Once
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescData = file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDesc
)

func file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescGZIP() []byte {
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescOnce.Do(func() {
		file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescData)
	})
	return file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDescData
}

var file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_goTypes = []interface{}{
	(*DownloadRequest)(nil),  // 0: downloadManager.downloadRequest
	(*DownloadResponse)(nil), // 1: downloadManager.downloadResponse
}
var file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_depIdxs = []int32{
	0, // 0: downloadManager.Downloader.Downloads:input_type -> downloadManager.downloadRequest
	1, // 1: downloadManager.Downloader.Downloads:output_type -> downloadManager.downloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_init() }
func file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_init() {
	if File_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_goTypes,
		DependencyIndexes: file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_depIdxs,
		MessageInfos:      file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_msgTypes,
	}.Build()
	File_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto = out.File
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_rawDesc = nil
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_goTypes = nil
	file_github_com_shashank_razor_DownloadManager_rpc_downloadManager_service_proto_depIdxs = nil
}
